version: 2.1
jobs:
  checks:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Migrate database
          command: yarn migrate
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install vercel
          command: "sudo npm install -g vercel"
      - run:
          name: Deploy
          command: vercel --token $CIRCLE_TOKEN --name $CIRCLE_PROJECT_REPONAME --prod --no-open

workflows:
  check-deploy:
    jobs:
      - checks
      - deploy