version: 2.1
jobs:
  checks:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Migrate database
          command: yarn migrate
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Deploy
          command: yarn deploy --token $VERCEL_TOKEN --name $VERCEL_NAME --prod

workflows:
  check-deploy:
    jobs:
      - checks
      - deploy
